server:
  port: 8888 # 伺服器的port號
spring:
  # spring datasource configuration 的配置
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  
  # For MySQL connection
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
   password: 12345

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
   
  
  
 #  datasource:
 #    driver-class-name: org.h2.Driver
 #     username: 'sa'
 #    password:
 #    url: 'jdbc:h2:mem:my_app'  # H2 的 JDBC URL, mem 表示使用記憶體, my_app 是資料庫的名稱
 #  h2:
 #    console:
 #      enabled: true  # 設定要啟用 H2 的 console 可以在瀏覽器上面查詢 table
 #     path: '/h2' # 瀏覽器 console 的 URL 路徑

    
   



